### ISSUE TITLE
Hi unable to play mp4

### ISSUE THREAD

**Issue by myselfgaurav** [jaeger25/Html5Video#29]
some mp4 not playing , i had mp4 vidoe that is not supported by android deault player, how can i play it

**Comment by odbol** [comment]
You should convert all your videos to WebM format - those are guaranteed to work on Android.

On January 22, 2015 8:33:48 PM PST, gaurav <notifications@github.com> wrote:
>some mp4 not playing , i had mp4 vidoe that is not supported by android
>deault player, how can i play it
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jaeger25/Html5Video/issues/29

Tyler Freeman
CTO, DrumPants, Inc.

Sent from mobile
